### ISSUE TITLE
Reliable information

### ISSUE THREAD

**Issue by Darthspider360** [Darthspider360/Bandaid#1]
**User Story:** As a user seeking help, I want reliable information about mental health so that I can better understand my options.

**Acceptance Criteria:**

- [ ] Create a page for external help links 
- [ ] Have a section for wellness tips 
- [ ] Have a section for emergency contacts
- [ ] Create a page for therapy descriptions

**Tasks:**

- [ ] gather resources for the external help links, wellness tips, emergency contacts and therapy descriptions
- [ ] find suitable images for each section to make it visually appealing
- [ ] write each section in an understandable way
- [ ] make sure these sections are responsive
