### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Darthspider360** [Darthspider360/BandAid#2]
**User Story:** As a user with disabilities, I want to navigate the site easily so that I can access the information I need without barriers.

**Acceptance Criteria:**

- [x] All images and non-text content must have descriptive alt text.
- [x] The site must use a readable font size and colour contrast.
- [ ] Allow users to change the site theme for their own comfortability. 

**Tasks:**

- [x] Add alt text to all images.
- [x] Test and adjust font size and colour contrast.
- [ ] add the ability to switch between light mode and dark mode.
