### ISSUE TITLE
Resources and Information

### ISSUE THREAD

**Issue by Darthspider360** [Darthspider360/BandAid#3]
**User Story:** As a user seeking help, I want reliable information about mental health so that I can better understand my condition and options.

**Acceptance Criteria:**

- [x] Content must be reviewed by mental health professionals.
- [x] Information must be presented in a clear, understandable manner.
- [x] Resources must be up-to-date.

**Tasks:**

- [x] Collaborate with mental health professionals to review content.
- [x] Write and format content for clarity.
- [x] Include the most up-to-date information
