### ISSUE TITLE
User-Friendly Design

### ISSUE THREAD

**Issue by Darthspider360** [Darthspider360/BandAid#4]
**User Story:** As a first-time visitor, I want a clean and intuitive design so that I can easily find what I'm looking for.

**Acceptance Criteria:**

- [x] The site must have a simple and intuitive navigation structure.
- [x] Content must be organized logically.
- [x] Users must be able to find information within three clicks.

**Tasks:**

- [x] Design and test navigation menus.
- [x] Organize content into categories.
- [x] Conduct user testing to ensure usability.
